name: Test Project Self Hosted
run-name: Building and Testing counter
on: [push]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu:latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - run: echo hello world
  test:
    timeout-minutes: 2
    runs-on: ubuntu:latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - run: pytest hw6_tests.py     
