name: Test MyPL
run-name: Building and Testing mypl
on: [push]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        run: echo hello world
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: install python
        run: sudo apt install python3
      - name: install pytest
        run: sudo pip install -U pytest
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: run tests
        run: make test
  lint:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install lintian
        run: sudo apt install lintian
      - name: install python
        run: sudo apt install python3
      - name: install pytest
        run: sudo pip install -U pytest
      - run: make lint
  build-deb:
    timeout-minutes: 2
    runs-on: ubuntu-latest 
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - run: make build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: counter-debian-package
          path: |
            mypl-v1.0.0.deb 
