name: Test Project Self Hosted
run-name: Building and Testing mypl
on: [push]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu:latest
    steps:
      - name: checkout repo
      - run: echo hello world
  test:
    timeout-minutes: 2
    runs-on: ubuntu:latest
    steps:
      - name: checkout repo
      - run: sudo apt install python3
      - run: sudo apt install pytest
      - run: pytest hw6_tests.py     
